### ISSUE TITLE
Rework left side panel - region, muns and parameter selection (step 2)

### ISSUE THREAD

**Issue by nesnoj** [stadt-land-energie-projekt/sl-app#101]
Region dropdown
- start: no selection
- classic dropdown (1 region only)
- on select
  - load muns of the region into muns dropdown and activate
  - zoom to bbox of region @henhuy 
  - activate parameter dropdown
  - show choropleth @henhuy 
- on unselect (reset button beside dropdown?)
  - (show popup to confirm?)
  - zoom out to Germany @henhuy 
  - deactivate dropdowns: parameter ("Darstellung") and parameter reference ("im Verhältnis zu")
  - remove muns from muns dropdown (and top nav) and deactivate

Muns dropdown
- multi select dropdown
- on select or remove: toogle in top nav list (-> use JS fct toggle region from @henhuy )
- on change @henhuy 
  - outline selected muns

---------------------------
Regions: municipalities
- Oderland-Spree: Erkner, Grünheide (Mark), Strausberg, Rüdersdorf bei Berlin
- Ingolstadt: Ingolstadt
- Nordhessen: Kassel
- Münsterland: Bocholt
- Kiel: Kiel
- Südwestsachsen: Zwickau

**Comment by henhuy** [comment]
Done in #123 
Zooming to bounding box not yet implemented - will be moved to new issue
