### ISSUE TITLE
Attach wizard and add sidepanel

### ISSUE THREAD

**Issue by josihoppe** [stadt-land-energie-projekt/sl-app#128]
Wizard should be attached in DOM to the top, should stay there when scrolling
- [x]  add scsss to attach the wizard and navbar

Sidepanel is going to be moved into base html, -> changes setup of map.html
on other views sidepanel is going to be used for info texts to explain what the views are doing
- [x]  move sidebar from map to base
- [x] adjust map to keep the compenents already there
- [x] add placeholders for explanations on the other views
- [x] don't show sidebar on start page

**Comment by josihoppe** [comment]
@nesnoj A question about the sidebar. There is a start / home page right now. Should that also have a sidebar or only all the templates from map until added_value ("Wertschöpfung") ?

**Comment by nesnoj** [comment]
Has not been defined yet.
If there's no sidebar at the moment, no need to add it right now..
