### ISSUE TITLE
Add banner showing selected municipalities

### ISSUE THREAD

**Issue by henhuy** [stadt-land-energie-projekt/sl-app#95]
In the future, the user should be able to see selected municipialites while directing through the app.
Current selection shall be visible within a banner on top of every upcoming view (map, details, Energiesystemoptimierung).
Selected municipalities are read from URL query (i.e. https://stadt-land-energie.apps.rl-institut.de?region=23&region=44&region=78).
Additionally, a "go back to selection view" button shall be added to banner.
Design of selected regions should look like multiple "tags":
![grafik](https://github.com/stadt-land-energie-projekt/sl-app/assets/17476051/a2e40d9d-c707-453c-a61a-83afdaeea7fd)

**Comment by henhuy** [comment]
First merge #99 
TODOS:
- [ ] Change "Next" button on map to include selected forms into get request
- [ ] Read selected forms in backend
- [ ] On details and other following pages select regions in banner and use use selected regions in logic below

**Comment by nesnoj** [comment]
Please add [x] to each mun box which remove the mun from the banner. Should only work in step 1.

**Comment by henhuy** [comment]
Done
